#!/usr/bin/env python3

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
import odoo

import pydevd
#TODO change to dockers default gateway
pydevd.settrace('10.43.5.24', port=11099, stdoutToServer=True, stderrToServer=True)

if __name__ == "__main__":
    odoo.cli.main()
